"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import DashboardNavigation from "../../components/DashboardNavigation";

type User = { id: string; email: string; notificationEmail: string; name: string; role: string; active: boolean; canViewAll: boolean; canManageCare: boolean; canAssignCare: boolean; canManageUsers: boolean; canAccessYouth: boolean; canManageYouth: boolean; canAccessHospital: boolean; canManageHospital: boolean; canAccessDiscipleship: boolean; canManageDiscipleship: boolean; allowedCategories: string[] };
type Audit = { id: string; actorName: string; action: string; carePerson: string; details: string; createdAt: string };
type ArchivedCare = { id: string; name: string; lane: string; archivedAt: string; archivedBy: string };
type Category = { id: string; name: string; createdBy: string };
type GoogleStatus = { configured: boolean; connected: boolean; senderEmail: string; connectedEmail: string; clientId: string };
type PlanningStatus = { configured: boolean; connected: boolean; connectorReady: boolean; clientId: string; connectedPersonName: string; organizationName: string; callbackUrl: string };

function googleResultMessage(result: string) {
  if (result === "connected") return "Google email connected successfully.";
  if (result === "token_invalid_client") return "Google rejected the Client Secret. Recopy the secret belonging to this exact Client ID, save it, and connect again.";
  if (result === "token_redirect_uri_mismatch") return "Google reports a redirect URI mismatch. Confirm the authorized redirect URI exactly matches the dashboard callback URL.";
  if (result === "token_invalid_grant") return "Google rejected or expired the authorization code. Click Connect Google account and complete the flow again without using Back or Refresh.";
  if (result === "missing_refresh_token") return "Google did not issue offline email access. Remove the app from your Google Account permissions, then connect it again.";
  if (result === "wrong_account") return "The approved Google account did not match kai@wakechurch.com. Connect again and select that account.";
  if (result === "state_error") return "The Google connection session expired. Start again from the Connect Google account button.";
  if (result.startsWith("token_")) return `Google token exchange failed: ${result.slice(6).replaceAll("_", " ")}.`;
  return "Google connection did not complete. Please start the connection again.";
}

function planningResultMessage(result: string) {
  if (result === "connected") return "Planning Center People connected successfully.";
  if (result === "state_error") return "The Planning Center connection session expired. Start the connection again.";
  if (result === "profile_error") return "Planning Center connected, but the authorized account could not be identified.";
  if (result === "configure") return "Save the Planning Center Client ID and Client Secret first.";
  if (result === "unauthorized") return "Global Admin access is required to connect Planning Center.";
  return `Planning Center connection failed: ${result.replaceAll("_", " ")}.`;
}

export default function AdminPage() {
  const [users, setUsers] = useState<User[]>([]), [events, setEvents] = useState<Audit[]>([]), [archived, setArchived] = useState<ArchivedCare[]>([]), [categories, setCategories] = useState<Category[]>([]), [categoryName, setCategoryName] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [google, setGoogle] = useState<GoogleStatus>({ configured: false, connected: false, senderEmail: "kai@wakechurch.com", connectedEmail: "", clientId: "" });
  const [googleDraft, setGoogleDraft] = useState({ clientId: "", clientSecret: "", senderEmail: "kai@wakechurch.com" });
  const [planning, setPlanning] = useState<PlanningStatus>({ configured: false, connected: false, connectorReady: false, clientId: "", connectedPersonName: "", organizationName: "", callbackUrl: "" });
  const [planningDraft, setPlanningDraft] = useState({ clientId: "", clientSecret: "" });
  const [connectorToken, setConnectorToken] = useState("");
  const [draft, setDraft] = useState({ name: "", email: "", password: "", role: "volunteer" });
  async function refresh() {
    const [u, a, r, c, g, p] = await Promise.all([fetch("/api/users", { cache: "no-store" }), fetch("/api/audit", { cache: "no-store" }), fetch("/api/care/archive", { cache: "no-store" }), fetch("/api/categories", { cache: "no-store" }), fetch("/api/google/settings", { cache: "no-store" }), fetch("/api/planning-center/settings", { cache: "no-store" })]);
    if (!u.ok || !a.ok || !r.ok || !c.ok || !g.ok || !p.ok) { setError("Global Admin access is required."); return; }
    setUsers((await u.json()).users ?? []); setEvents((await a.json()).events ?? []); setArchived((await r.json()).items ?? []); setCategories((await c.json()).categories ?? []);
    const googleResult = await g.json() as GoogleStatus; setGoogle(googleResult); setGoogleDraft(current => ({ ...current, clientId: googleResult.clientId, senderEmail: googleResult.senderEmail }));
    const planningResult = await p.json() as PlanningStatus; setPlanning(planningResult); setPlanningDraft(current => ({ ...current, clientId: planningResult.clientId }));
  }
  useEffect(() => { const timer = window.setTimeout(() => { void refresh(); const params = new URLSearchParams(window.location.search); const googleResult = params.get("google"); const planningResult = params.get("planning"); if (googleResult === "connected") setNotice(googleResultMessage(googleResult)); else if (googleResult) setError(googleResultMessage(googleResult)); if (planningResult === "connected") setNotice(planningResultMessage(planningResult)); else if (planningResult) setError(planningResultMessage(planningResult)); }, 0); return () => window.clearTimeout(timer); }, []);
  async function create(event: FormEvent) {
    event.preventDefault(); setError(""); setNotice("");
    const response = await fetch("/api/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) });
    const result = await response.json() as { error?: string };
    if (!response.ok) { setError(result.error ?? "Account could not be created."); return; }
    setNotice(`Account created for ${draft.email}. Share the temporary password separately.`); setDraft({ name: "", email: "", password: "", role: "volunteer" }); await refresh();
  }
  async function update(user: User, changes: Partial<User> & { password?: string }) {
    const response = await fetch("/api/users", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: user.id, ...changes }) });
    const result = await response.json() as { error?: string }; if (!response.ok) { setError(result.error ?? "Account could not be updated."); return; } await refresh();
  }
  async function restore(id: string) {
    const response = await fetch("/api/care/archive", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) });
    if (!response.ok) { setError("Care record could not be restored."); return; }
    setNotice("Care record restored to the dashboard."); await refresh();
  }
  async function addCategory(event: FormEvent) {
    event.preventDefault(); setError("");
    const response = await fetch("/api/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: categoryName }) });
    const result = await response.json() as { error?: string };
    if (!response.ok) { setError(result.error ?? "Category could not be added."); return; }
    setNotice(`Added care category: ${categoryName}`); setCategoryName(""); await refresh();
  }
  async function saveGoogle(event: FormEvent) {
    event.preventDefault(); setError(""); setNotice("");
    const response = await fetch("/api/google/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(googleDraft) });
    const result = await response.json() as { error?: string };
    if (!response.ok) { setError(result.error ?? "Google settings could not be saved."); return; }
    setGoogleDraft(current => ({ ...current, clientSecret: "" })); setNotice("Google credentials saved securely. Continue by connecting the sender account."); await refresh();
  }
  async function savePlanning(event: FormEvent) {
    event.preventDefault(); setError(""); setNotice(""); setConnectorToken("");
    const response = await fetch("/api/planning-center/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(planningDraft) });
    const result = await response.json() as { error?: string };
    if (!response.ok) { setError(result.error ?? "Planning Center settings could not be saved."); return; }
    setPlanningDraft(current => ({ ...current, clientSecret: "" })); setNotice("Planning Center credentials saved securely. Continue by connecting the authorized account."); await refresh();
  }
  async function generateConnectorToken() {
    setError(""); setNotice(""); setConnectorToken("");
    const response = await fetch("/api/planning-center/connector-token", { method: "POST" });
    const result = await response.json() as { token?: string; error?: string };
    if (!response.ok || !result.token) { setError(result.error ?? "Connector key could not be created."); return; }
    setConnectorToken(result.token); setNotice("A new private ChatGPT connector key was created. The previous key no longer works.");
  }
  return <main className="admin-shell"><header className="admin-header"><div><p className="section-label">Shepherding · Security</p><h1>Global Admin</h1><p>Manage volunteer access, permissions, and accountability.</p></div><Link className="primary-button" href="/">Return to care dashboard</Link></header>
    <div className="admin-navigation-wrap"><DashboardNavigation globalAdmin /></div>
    {error && <div className="error-banner">{error}</div>}{notice && <div className="notice-banner">{notice}</div>}
    <section className="admin-grid"><article className="panel admin-card"><h2>Add a volunteer</h2><form onSubmit={create} className="admin-form"><label>Name<input required value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Login email<input type="email" required value={draft.email} onChange={e => setDraft({ ...draft, email: e.target.value })} /></label><label>Temporary password<input type="password" minLength={12} required value={draft.password} onChange={e => setDraft({ ...draft, password: e.target.value })} placeholder="At least 12 characters" /></label><label>Role<select value={draft.role} onChange={e => setDraft({ ...draft, role: e.target.value })}><option value="volunteer">Volunteer</option><option value="global_admin">Global Admin</option></select></label><button className="primary-button" type="submit">Create account</button></form></article>
      <article className="panel admin-card wide"><h2>Accounts & permissions</h2><div className="admin-user-list">{users.map(user => <div className="admin-user" key={user.id}><div><strong>{user.name}</strong><span>{user.email} · {user.role.replace("_", " ")}</span></div><label><input type="checkbox" checked={user.active} onChange={e => void update(user, { active: e.target.checked })} /> Active</label><label><input type="checkbox" checked={user.canViewAll} onChange={e => void update(user, { canViewAll: e.target.checked })} /> View all care</label><label><input type="checkbox" checked={user.canManageCare} onChange={e => void update(user, { canManageCare: e.target.checked })} /> Update care</label><label><input type="checkbox" checked={user.canAssignCare} onChange={e => void update(user, { canAssignCare: e.target.checked })} /> Assign care</label><label><input type="checkbox" checked={user.canAccessYouth} onChange={e => void update(user, { canAccessYouth: e.target.checked })} /> Youth access</label><label><input type="checkbox" checked={user.canManageYouth} onChange={e => void update(user, { canManageYouth: e.target.checked })} /> Manage Youth</label><label><input type="checkbox" checked={user.canAccessHospital} onChange={e => void update(user, { canAccessHospital: e.target.checked })} /> Hospital access</label><label><input type="checkbox" checked={user.canManageHospital} onChange={e => void update(user, { canManageHospital: e.target.checked })} /> Manage Hospital</label><label><input type="checkbox" checked={user.canAccessDiscipleship} onChange={e => void update(user, { canAccessDiscipleship: e.target.checked })} /> Discipleship access</label><label><input type="checkbox" checked={user.canManageDiscipleship} onChange={e => void update(user, { canManageDiscipleship: e.target.checked })} /> Manage Discipleship</label><label><input type="checkbox" checked={user.canManageUsers} onChange={e => void update(user, { canManageUsers: e.target.checked })} /> Manage users</label><button className="text-button" onClick={() => { const password = prompt("New temporary password (12+ characters)"); if (password) void update(user, { password }); }}>Reset password</button></div>)}</div></article></section>
    <section className="panel admin-card audit-card"><h2>Wake Youth team access</h2><p className="permission-note">Youth access lets a volunteer see only students and staff care assigned to them. Manage Youth lets a leader add students, assign care owners, and manage the staff-care lane.</p><div className="category-permission-list">{users.filter(user => user.canAccessYouth || user.canManageYouth || user.canManageUsers).map(user => <div className="category-permission-row" key={user.id}><div><strong>{user.name}</strong><span>{user.email}</span></div><div><label><input type="checkbox" checked={user.canAccessYouth} onChange={event => void update(user, { canAccessYouth: event.target.checked })} /> Wake Youth access</label><label><input type="checkbox" checked={user.canManageYouth} onChange={event => void update(user, { canManageYouth: event.target.checked })} /> Add and assign youth care</label></div></div>)}</div></section>
    <section className="panel admin-card audit-card"><h2>Hospital Team access</h2><p className="permission-note">Hospital access shows shared resources and only the hospital care assigned to that volunteer. Manage Hospital can assign care, publish resources, and manage the Hospital Team.</p><div className="category-permission-list">{users.filter(user => user.canAccessHospital || user.canManageHospital || user.canManageUsers).map(user => <div className="category-permission-row" key={user.id}><div><strong>{user.name}</strong><span>{user.email}</span></div><div><label><input type="checkbox" checked={user.canAccessHospital} onChange={event => void update(user, { canAccessHospital: event.target.checked })} /> Hospital Team access</label><label><input type="checkbox" checked={user.canManageHospital} onChange={event => void update(user, { canManageHospital: event.target.checked })} /> Assign care and publish resources</label></div></div>)}</div></section>
    <section className="panel admin-card audit-card"><h2>Wake Discipleship access</h2><p className="permission-note">Discipleship access shows only people assigned to that disciple maker. Manage Discipleship can create assignments, manage the team, and complete third-meeting coach follow-ups.</p><div className="category-permission-list">{users.filter(user => user.canAccessDiscipleship || user.canManageDiscipleship || user.canManageUsers).map(user => <div className="category-permission-row" key={user.id}><div><strong>{user.name}</strong><span>{user.email}</span></div><div><label><input type="checkbox" checked={user.canAccessDiscipleship} onChange={event => void update(user, { canAccessDiscipleship: event.target.checked })} /> Wake Discipleship access</label><label><input type="checkbox" checked={user.canManageDiscipleship} onChange={event => void update(user, { canManageDiscipleship: event.target.checked })} /> Assign people and coach disciple makers</label></div></div>)}</div></section>
    <section className="panel admin-card audit-card"><h2>Volunteer category visibility</h2><p className="permission-note">A volunteer sees only care assigned to them inside the categories checked here. With no categories checked, they see no care records.</p><div className="category-permission-list">{users.filter(user => !user.canViewAll).map(user => <div className="category-permission-row" key={user.id}><div><strong>{user.name}</strong><span>{user.email}</span></div><div>{categories.map(category => <label key={category.id}><input type="checkbox" checked={user.allowedCategories.includes(category.name)} onChange={event => { const next = event.target.checked ? [...user.allowedCategories, category.name] : user.allowedCategories.filter(name => name !== category.name); void update(user, { allowedCategories: next }); }} /> {category.name}</label>)}</div></div>)}</div></section>
    <section className="panel admin-card audit-card"><h2>Archived care · recoverable</h2><div className="archive-list">{archived.length ? archived.map(item => <div key={item.id}><div><strong>{item.name}</strong><span>{item.lane} · Archived by {item.archivedBy || "Global Admin"} on {new Date(item.archivedAt).toLocaleString()}</span></div><button className="text-button" onClick={() => void restore(item.id)}>Restore</button></div>) : <p>No archived care records.</p>}</div></section>
    <section className="panel admin-card audit-card"><h2>Care categories</h2><form className="category-form" onSubmit={addCategory}><input required value={categoryName} onChange={event => setCategoryName(event.target.value)} placeholder="Add your own category" /><button className="primary-button" type="submit">Add category</button></form><div className="category-list">{categories.map(category => <span key={category.id}>{category.name}</span>)}</div></section>
    <section className="panel admin-card audit-card"><div className="google-heading"><div><h2>Google assignment emails</h2><p>Automatically notify the assigned volunteer from kai@wakechurch.com.</p></div><span className={google.connected ? "connection-status connected" : "connection-status"}>{google.connected ? `Connected: ${google.connectedEmail}` : google.configured ? "Credentials saved · connection needed" : "Not configured"}</span></div><form className="google-form" onSubmit={saveGoogle} autoComplete="off"><label>OAuth Client ID<input required autoComplete="off" data-lpignore="true" value={googleDraft.clientId} onChange={event => setGoogleDraft({ ...googleDraft, clientId: event.target.value })} placeholder="…apps.googleusercontent.com" /></label><label>OAuth Client Secret<input type="password" autoComplete="new-password" data-lpignore="true" required={!google.configured} value={googleDraft.clientSecret} onChange={event => setGoogleDraft({ ...googleDraft, clientSecret: event.target.value })} placeholder={google.configured ? "Enter again only to replace credentials" : "Paste directly from Google Cloud"} /></label><label>Sender email<input type="email" autoComplete="off" required value={googleDraft.senderEmail} onChange={event => setGoogleDraft({ ...googleDraft, senderEmail: event.target.value })} /></label><div className="google-actions"><button className="primary-button" type="submit">Save Google credentials</button>{google.configured && <a className="primary-button secondary" href="/api/google/connect">Connect Google account</a>}</div></form><p className="security-note">The Client Secret and Google refresh token are encrypted before database storage and are never displayed again.</p></section>
    <section className="panel admin-card audit-card"><div className="google-heading"><div><h2>Planning Center People</h2><p>Secure person lookup and confirmed workflow changes for the dashboard and ChatGPT Work.</p></div><span className={planning.connected ? "connection-status connected" : "connection-status"}>{planning.connected ? `Connected: ${planning.organizationName}` : planning.configured ? "Credentials saved · connection needed" : "Not configured"}</span></div><form className="google-form" onSubmit={savePlanning} autoComplete="off"><label>OAuth Client ID<input required autoComplete="off" data-lpignore="true" value={planningDraft.clientId} onChange={event => setPlanningDraft({ ...planningDraft, clientId: event.target.value })} /></label><label>OAuth Client Secret<input type="password" autoComplete="new-password" data-lpignore="true" required={!planning.configured} value={planningDraft.clientSecret} onChange={event => setPlanningDraft({ ...planningDraft, clientSecret: event.target.value })} placeholder={planning.configured ? "Enter again only to replace credentials" : "Paste directly from Planning Center"} /></label><label>Authorized redirect URI<input readOnly value={planning.callbackUrl} onFocus={event => event.currentTarget.select()} /></label><div className="google-actions"><button className="primary-button" type="submit">Save Planning Center credentials</button>{planning.configured && <a className="primary-button secondary" href="/api/planning-center/connect">Connect Planning Center</a>}{planning.connected && <Link className="primary-button secondary" href="/planning-center">Open People workspace</Link>}</div></form>{planning.connected && <div className="connector-setup"><div><strong>Private ChatGPT Work connector</strong><span>{planning.connectorReady ? "A connector key exists. Generating another will revoke it." : "Create the one-time key after Planning Center is connected."}</span></div><button className="secondary-button" onClick={() => void generateConnectorToken()}>Generate connector key</button></div>}{connectorToken && <div className="secret-once"><strong>Copy this key now—it will not be shown again.</strong><code>{connectorToken}</code><button className="text-button" onClick={() => void navigator.clipboard.writeText(connectorToken)}>Copy key</button></div>}<p className="security-note">Only the People scope is requested. Planning Center tokens are encrypted; medical notes, giving, and background-check data are excluded from this integration.</p></section>
    <section className="panel admin-card audit-card"><h2>Recent audit activity</h2><div className="audit-list">{events.length ? events.map(event => <div key={event.id}><time>{new Date(event.createdAt).toLocaleString()}</time><strong>{event.actorName}</strong><span>{event.action}{event.carePerson ? ` · ${event.carePerson}` : ""}{event.details ? ` · ${event.details}` : ""}</span></div>) : <p>No activity yet.</p>}</div></section>
  </main>;
}
