import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const careItems = sqliteTable("care_items", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull().default(""),
  lane: text("lane").notNull(),
  need: text("need").notNull().default(""),
  lastContact: text("last_contact").notNull().default(""),
  nextAction: text("next_action").notNull().default(""),
  followUpDate: text("follow_up_date").notNull().default(""),
  priority: text("priority").notNull().default("Normal"),
  status: text("status").notNull().default("Open"),
  notes: text("notes").notNull().default(""),
  assignedTo: text("assigned_to").notNull().default(""),
  assignedEmail: text("assigned_email").notNull().default(""),
  assignedUserId: text("assigned_user_id").notNull().default(""),
  archivedAt: text("archived_at").notNull().default(""),
  archivedBy: text("archived_by").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const careCategories = sqliteTable("care_categories", {
  id: text("id").primaryKey(),
  name: text("name").notNull().unique(),
  createdBy: text("created_by").notNull().default("System"),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const googleEmailSettings = sqliteTable("google_email_settings", {
  id: text("id").primaryKey(),
  clientId: text("client_id").notNull(),
  encryptedClientSecret: text("encrypted_client_secret").notNull(),
  clientSecretIv: text("client_secret_iv").notNull(),
  encryptedRefreshToken: text("encrypted_refresh_token").notNull().default(""),
  refreshTokenIv: text("refresh_token_iv").notNull().default(""),
  senderEmail: text("sender_email").notNull(),
  connectedEmail: text("connected_email").notNull().default(""),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const planningCenterSettings = sqliteTable("planning_center_settings", {
  id: text("id").primaryKey(),
  clientId: text("client_id").notNull(),
  encryptedClientSecret: text("encrypted_client_secret").notNull(),
  clientSecretIv: text("client_secret_iv").notNull(),
  encryptedAccessToken: text("encrypted_access_token").notNull().default(""),
  accessTokenIv: text("access_token_iv").notNull().default(""),
  encryptedRefreshToken: text("encrypted_refresh_token").notNull().default(""),
  refreshTokenIv: text("refresh_token_iv").notNull().default(""),
  tokenExpiresAt: text("token_expires_at").notNull().default(""),
  connectedPersonId: text("connected_person_id").notNull().default(""),
  connectedPersonName: text("connected_person_name").notNull().default(""),
  organizationId: text("organization_id").notNull().default(""),
  organizationName: text("organization_name").notNull().default(""),
  connectorTokenHash: text("connector_token_hash").notNull().default(""),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  notificationEmail: text("notification_email").notNull().default(""),
  name: text("name").notNull(),
  role: text("role").notNull().default("volunteer"),
  passwordHash: text("password_hash").notNull(),
  passwordSalt: text("password_salt").notNull(),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  canViewAll: integer("can_view_all", { mode: "boolean" }).notNull().default(false),
  canManageCare: integer("can_manage_care", { mode: "boolean" }).notNull().default(true),
  canAssignCare: integer("can_assign_care", { mode: "boolean" }).notNull().default(false),
  canManageUsers: integer("can_manage_users", { mode: "boolean" }).notNull().default(false),
  canAccessYouth: integer("can_access_youth", { mode: "boolean" }).notNull().default(false),
  canManageYouth: integer("can_manage_youth", { mode: "boolean" }).notNull().default(false),
  canAccessHospital: integer("can_access_hospital", { mode: "boolean" }).notNull().default(false),
  canManageHospital: integer("can_manage_hospital", { mode: "boolean" }).notNull().default(false),
  canAccessDiscipleship: integer("can_access_discipleship", { mode: "boolean" }).notNull().default(false),
  canManageDiscipleship: integer("can_manage_discipleship", { mode: "boolean" }).notNull().default(false),
  allowedCategories: text("allowed_categories").notNull().default("[]"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const youthCare = sqliteTable("youth_care", {
  id: text("id").primaryKey(),
  personType: text("person_type").notNull().default("student"),
  name: text("name").notNull(),
  subjectUserId: text("subject_user_id").notNull().default(""),
  school: text("school").notNull().default(""),
  birthday: text("birthday").notNull().default(""),
  category: text("category").notNull().default("Discipleship"),
  need: text("need").notNull().default(""),
  lastContact: text("last_contact").notNull().default(""),
  nextAction: text("next_action").notNull().default(""),
  followUpDate: text("follow_up_date").notNull().default(""),
  status: text("status").notNull().default("Open"),
  notes: text("notes").notNull().default(""),
  assignedUserId: text("assigned_user_id").notNull().default(""),
  assignedTo: text("assigned_to").notNull().default(""),
  birthdayAcknowledgedYear: integer("birthday_acknowledged_year").notNull().default(0),
  archivedAt: text("archived_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const hospitalCare = sqliteTable("hospital_care", {
  id: text("id").primaryKey(),
  personName: text("person_name").notNull(),
  age: text("age").notNull().default(""),
  hospitalName: text("hospital_name").notNull(),
  hospitalAddress: text("hospital_address").notNull(),
  roomNumber: text("room_number").notNull().default(""),
  situation: text("situation").notNull().default(""),
  incidentDate: text("incident_date").notNull().default(""),
  expectedDischargeDate: text("expected_discharge_date").notNull().default(""),
  dischargedAt: text("discharged_at").notNull().default(""),
  contactName: text("contact_name").notNull().default(""),
  contactPhone: text("contact_phone").notNull().default(""),
  contactEmail: text("contact_email").notNull().default(""),
  relationship: text("relationship").notNull().default(""),
  visitGuidance: text("visit_guidance").notNull().default(""),
  notes: text("notes").notNull().default(""),
  lastContact: text("last_contact").notNull().default(""),
  nextAction: text("next_action").notNull().default(""),
  followUpDate: text("follow_up_date").notNull().default(""),
  status: text("status").notNull().default("Open"),
  assignedUserId: text("assigned_user_id").notNull().default(""),
  assignedTo: text("assigned_to").notNull().default(""),
  archivedAt: text("archived_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const hospitalMilestones = sqliteTable("hospital_milestones", {
  id: text("id").primaryKey(),
  hospitalCareId: text("hospital_care_id").notNull(),
  kind: text("kind").notNull(),
  label: text("label").notNull(),
  dueDate: text("due_date").notNull().default(""),
  status: text("status").notNull().default("Open"),
  completedAt: text("completed_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const hospitalResources = sqliteTable("hospital_resources", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  resourceType: text("resource_type").notNull().default("Article"),
  summary: text("summary").notNull().default(""),
  url: text("url").notNull(),
  publishedBy: text("published_by").notNull().default(""),
  archivedAt: text("archived_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const discipleshipRelationships = sqliteTable("discipleship_relationships", {
  id: text("id").primaryKey(),
  ministry: text("ministry").notNull().default("Wake Men"),
  discipleName: text("disciple_name").notNull(),
  disciplePhone: text("disciple_phone").notNull().default(""),
  discipleEmail: text("disciple_email").notNull().default(""),
  discipleMakerUserId: text("disciple_maker_user_id").notNull(),
  discipleMakerName: text("disciple_maker_name").notNull(),
  startedAt: text("started_at").notNull().default(""),
  lastContact: text("last_contact").notNull().default(""),
  nextMeetupDate: text("next_meetup_date").notNull().default(""),
  growthNeeded: text("growth_needed").notNull().default("[]"),
  growthSeen: text("growth_seen").notNull().default("[]"),
  notes: text("notes").notNull().default(""),
  meetupCount: integer("meetup_count").notNull().default(0),
  coachContactedAt: text("coach_contacted_at").notNull().default(""),
  status: text("status").notNull().default("Active"),
  archivedAt: text("archived_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const maternalCare = sqliteTable("maternal_care", {
  id: text("id").primaryKey(),
  momName: text("mom_name").notNull(),
  email: text("email").notNull().default(""),
  stage: text("stage").notNull().default("trying"),
  dueDate: text("due_date").notNull().default(""),
  babyBornDate: text("baby_born_date").notNull().default(""),
  babyName: text("baby_name").notNull().default(""),
  mealTrainFormUrl: text("meal_train_form_url").notNull().default(""),
  notes: text("notes").notNull().default(""),
  assignedUserId: text("assigned_user_id").notNull().default(""),
  assignedTo: text("assigned_to").notNull().default(""),
  archivedAt: text("archived_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const maternalMilestones = sqliteTable("maternal_milestones", {
  id: text("id").primaryKey(),
  maternalCareId: text("maternal_care_id").notNull(),
  kind: text("kind").notNull(),
  label: text("label").notNull(),
  dueDate: text("due_date").notNull(),
  status: text("status").notNull().default("Open"),
  completedAt: text("completed_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const careTeamRequests = sqliteTable("care_team_requests", {
  id: text("id").primaryKey(),
  source: text("source").notNull(),
  assignmentId: text("assignment_id").notNull(),
  personName: text("person_name").notNull(),
  senderUserId: text("sender_user_id").notNull(),
  senderName: text("sender_name").notNull(),
  kind: text("kind").notNull().default("message"),
  message: text("message").notNull(),
  urgency: text("urgency").notNull().default("normal"),
  status: text("status").notNull().default("Open"),
  resolvedBy: text("resolved_by").notNull().default(""),
  resolvedAt: text("resolved_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const sessions = sqliteTable("sessions", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  tokenHash: text("token_hash").notNull().unique(),
  expiresAt: text("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const auditEvents = sqliteTable("audit_events", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  actorName: text("actor_name").notNull(),
  action: text("action").notNull(),
  careItemId: text("care_item_id").notNull().default(""),
  carePerson: text("care_person").notNull().default(""),
  details: text("details").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
